# Generated by Django 2.2.7 on 2019-11-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_post_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_edited',
            field=models.DateField(),
        ),
    ]
