# Generated by Django 2.2.7 on 2019-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_subform'),
    ]

    operations = [
        migrations.AddField(
            model_name='subform',
            name='name',
            field=models.CharField(default=23, max_length=200),
            preserve_default=False,
        ),
    ]
