# Generated by Django 2.2.7 on 2019-11-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20191112_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Postzzz'},
        ),
    ]
