# Generated by Django 2.2.7 on 2019-11-14 01:50

from django.db import migrations, models
import index.validators


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20191112_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='subform',
            name='email',
            field=models.EmailField(max_length=200, validators=[index.validators.validate_domain_email]),
        ),
    ]
