# Generated by Django 2.2.7 on 2019-11-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20191113_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
