# Generated by Django 2.2.7 on 2019-11-19 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_projects_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='url',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='projects',
            name='live_project_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
