# Generated by Django 2.2.7 on 2019-11-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20191119_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(max_length=200),
        ),
    ]
